/*
 * generated by Xtext
 */
package org.jboss.byteman.eclipse.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class BytemanUiModule extends org.jboss.byteman.eclipse.ui.AbstractBytemanUiModule {
	public BytemanUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
