/*
* generated by Xtext
*/
package org.jboss.byteman.eclipse.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.jboss.byteman.eclipse.services.BytemanGrammarAccess;

public class BytemanParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private BytemanGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_BM_COMMENT");
	}
	
	@Override
	protected org.jboss.byteman.eclipse.parser.antlr.internal.InternalBytemanParser createParser(XtextTokenStream stream) {
		return new org.jboss.byteman.eclipse.parser.antlr.internal.InternalBytemanParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "DomainModel";
	}
	
	public BytemanGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(BytemanGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
