/*
* generated by Xtext
*/
package org.jboss.byteman.eclipse.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class BytemanOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
