/*
* generated by Xtext
*/
package org.jboss.byteman.eclipse.ui.contentassist;

import org.jboss.byteman.eclipse.ui.contentassist.AbstractBytemanProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class BytemanProposalProvider extends AbstractBytemanProposalProvider {

}
