/*
 * generated by Xtext
 */
package org.jboss.byteman.eclipse.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class BytemanExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return org.jboss.byteman.eclipse.ui.internal.BytemanActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return org.jboss.byteman.eclipse.ui.internal.BytemanActivator.getInstance().getInjector("org.jboss.byteman.eclipse.Byteman");
	}
	
}
