/*
 * generated by Xtext
 */
package org.jboss.byteman.eclipse;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class BytemanRuntimeModule extends org.jboss.byteman.eclipse.AbstractBytemanRuntimeModule {

	private static String bytemanHome = "";
	
	public static void setBytemanHome(String newValue) {
		bytemanHome = newValue;
	}
	public static String getBytemanHome()
	{
		return bytemanHome;
	}
}
